services:
  - type: web
    name: recipe-app
    env: node
    buildCommand: npm install && npm install --prefix client && npm run build --prefix client
    startCommand: node server/index.js
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production