services:
  - type: web
    name: recipe-app
    env: node
    buildCommand: npm install && npm install --prefix client && npm run build --prefix client
    startCommand: npm start
    nodeVersion: 18.x
    routes:
      - type: rewrite
        source: /*
        destination: /